image: node:20

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - build_job
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
